application: ezscreens-hrd
version: 5
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: django
  version: latest

handlers:
- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /images
  static_dir: public/images

- url: /applet
  static_dir: public/applet

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt
  mime_type: text/plain

- url: /favicon.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico
  mime_type: image/png

- url: /my
  script: main.application
  login: required

- url: .*
  script: main.application

builtins:
- appstats: on
- remote_api: on
